apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: ndbservers.ndb.nutanix.com
spec:
  group: ndb.nutanix.com
  names:
    kind: NDBServer
    listKind: NDBServerList
    plural: ndbservers
    shortNames:
    - ndb
    - ndbs
    singular: ndbserver
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .status.lastUpdated
      name: Updated At
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NDBServer is the Schema for the ndbservers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NDBServerSpec defines the desired state of NDBServer
            properties:
              credentialSecret:
                type: string
              server:
                type: string
              skipCertificateVerification:
                default: false
                description: Skip server's certificate and hostname verification
                type: boolean
            required:
            - credentialSecret
            - server
            type: object
          status:
            description: NDBServerStatus defines the observed state of NDBServer
            properties:
              databases:
                additionalProperties:
                  description: Database related info to be stored in the status field
                    of the NDB CR
                  properties:
                    dbServerId:
                      type: string
                    id:
                      type: string
                    ipAddress:
                      type: string
                    name:
                      type: string
                    status:
                      type: string
                    timeMachineId:
                      type: string
                    type:
                      type: string
                  required:
                  - dbServerId
                  - id
                  - ipAddress
                  - name
                  - status
                  - timeMachineId
                  - type
                  type: object
                type: object
              lastUpdated:
                type: string
              reconcileCounter:
                properties:
                  database:
                    type: integer
                required:
                - database
                type: object
              status:
                type: string
            required:
            - databases
            - lastUpdated
            - reconcileCounter
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}