apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cert-manager-test/selfsigned-cert
    controller-gen.kubebuilder.io/version: v0.9.2
  name: databases.ndb.nutanix.com
spec:
  # Commenting out this as Helm templating logic is not supported inside the crds/ directory and this is not critical for NDB operator
  # The webhook is also responsible for implementing a conversion over versions in the cert-manager CustomResources (cert-manager.io). 
  # This means that multiple API versions can be supported simultaneously; from v1alpha2 through to v1. This makes it possible to rely 
  # on a particular version of our configuration schema. More information available at https://cert-manager.io/docs/concepts/webhook/
  # conversion:
  #   strategy: Webhook
  #   webhook:
  #     clientConfig:
  #       service:
  #         name: ndb-operator-webhook-service
  #         namespace: {{.Release.Namespace}}
  #         path: /convert
  #     conversionReviewVersions:
  #     - v1
  group: ndb.nutanix.com
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    shortNames:
    - db
    - dbs
    singular: database
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.ipAddress
      name: IP Address
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .status.type
      name: Type
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Database is the Schema for the databases API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DatabaseSpec defines the desired state of Database
            properties:
              databaseInstance:
                description: Database instance specific details
                properties:
                  credentialSecret:
                    description: Name of the secret holding the credentials for the
                      database instance (password and ssh key)
                    type: string
                  databaseInstanceName:
                    description: Name of the database instance
                    type: string
                  databaseNames:
                    description: Name(s) of the database(s) to be provisiond inside
                      the database instance default [ "database_one", "database_two",
                      "database_three" ]
                    items:
                      type: string
                    type: array
                  profiles:
                    properties:
                      compute:
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                        type: object
                      dbParam:
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                        type: object
                      dbParamInstance:
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                        type: object
                      network:
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                        type: object
                      software:
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                        type: object
                    type: object
                  size:
                    description: Size of the database instance, minimum 10 (GBs)
                    type: integer
                  timeMachine:
                    description: Information related to time machine that is to be
                      associated with this database
                    properties:
                      dailySnapshotTime:
                        description: Daily snapshot time in HH:MM:SS (24 hour format)
                        type: string
                      description:
                        type: string
                      logCatchUpFrequency:
                        description: Log catch up frequency in minutes
                        type: integer
                      monthlySnapshotDay:
                        description: Day of the month for monthly snapshot
                        type: integer
                      name:
                        type: string
                      quarterlySnapshotMonth:
                        description: Start month for the quarterly snapshot Jan =>
                          Jan, Apr, Jul, Oct. Feb => Feb, May, Aug, Nov. Mar => Mar,
                          Jun, Sep, Dec.
                        type: string
                      sla:
                        description: Name of the SLA to be used, default NONE
                        type: string
                      snapshotsPerDay:
                        description: Number of snapshots per day
                        type: integer
                      weeklySnapshotDay:
                        description: Day of the week for weekly snapshot
                        type: string
                    type: object
                  timezone:
                    description: default UTC
                    type: string
                  type:
                    type: string
                required:
                - credentialSecret
                - databaseInstanceName
                - size
                - type
                type: object
              ndb:
                description: Details of the NDB installation
                properties:
                  clusterId:
                    type: string
                  credentialSecret:
                    description: Name of the secret holding the credentials for NDB
                      (username and password)
                    type: string
                  server:
                    description: NDB Server URL
                    type: string
                  skipCertificateVerification:
                    description: Skip server's certificate and hostname verification
                    type: boolean
                required:
                - clusterId
                - credentialSecret
                - server
                - skipCertificateVerification
                type: object
            required:
            - databaseInstance
            - ndb
            type: object
          status:
            description: DatabaseStatus defines the observed state of Database
            properties:
              dbServerId:
                type: string
              id:
                type: string
              ipAddress:
                type: string
              status:
                type: string
              type:
                type: string
            required:
            - dbServerId
            - id
            - ipAddress
            - status
            - type
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
