apiVersion: v1
name: nutanix-csi-storage
version: 2.2.0-rc.5
kubeVersion: ">= 1.13.0"
description: A Helm chart for installing Nutanix CSI Volume Driver
home: https://github.com/nutanix/helm
maintainers:
- name: tuxtof
icon: https://avatars2.githubusercontent.com/u/6165865?s=200&v=4
appVersion: "2.2.0"
keywords:
  - Nutanix
  - Storage
  - Volumes
  - Files
  - StorageClass
  - CentOS
  - Ubuntu
  - Openshift4
