apiVersion: v1
name: nutanix-csi-storage
version: 1.0.0
kubeVersion: ">= 1.13.0"
description: A Helm chart for installing Nutanix CSI Volume Driver
home: https://github.com/nutanix/helm
maintainers:
- name: tuxtof
icon: https://avatars2.githubusercontent.com/u/6165865?s=200&v=4
appVersion: "1.0.1"
keywords:
  - Nutanix
  - Storage
  - Volumes
  - Files
  - StorageClass
  - CentOS
  - Ubuntu
