apiVersion: v1
kind: ConfigMap
metadata:
  name: ntnx-init-configmap
  namespace: ntnx-system
data:
  supportedPCVersions: {{ .Values.supportedPCVersions }}
  kubernetesClusterDeploymentType: {{ .Values.kubernetesClusterDeploymentType }}
