apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: ndb-operator
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: issuer
    app.kubernetes.io/part-of: ndb-operator
  name: {{ include "ndb-operator.fullname" . }}-selfsigned-issuer
  namespace: {{.Release.Namespace}}
spec:
  selfSigned: {}

