apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ndb-operator-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ndb-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "ndb-operator.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
